# This makefile can be used to regenerate the protobuf files.
#
# Prerequisites:
#   protoc               https://github.com/protocolbuffers/protobuf
#   protoc-gen-go        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
#   protoc-gen-go-grpc   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
#
# Run: make -f Makefile.update-protos
#
# Note: the standard protoc-gen-go runtime always embeds state/sizeCache/
# unknownFields per message and has no equivalent of the old gogo vanity
# options. These messages have no map fields, so proto.Marshal output is
# already byte-stable across marshal/unmarshal cycles (add
# proto.MarshalOptions{Deterministic: true} if a map field is ever added).
# The gogo memory-footprint trimming has no standard equivalent.

PROTOS := $(wildcard \
	errbase/internal/*.proto \
	errorspb/*.proto \
	extgrpc/*.proto \
	exthttp/*.proto \
	grpc/*.proto \
	markers/internal/*.proto \
)
GO_SOURCES = $(PROTOS:.proto=.pb.go)

all: $(PROTOS)
	protoc -I. \
		--go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative \
		$(PROTOS)
	gofmt -s -w $(GO_SOURCES)
