// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: grpc/echoer.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_grpc_echoer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_echoer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_echoer_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EchoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoReply) Reset() {
	*x = EchoReply{}
	mi := &file_grpc_echoer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoReply) ProtoMessage() {}

func (x *EchoReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_echoer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoReply.ProtoReflect.Descriptor instead.
func (*EchoReply) Descriptor() ([]byte, []int) {
	return file_grpc_echoer_proto_rawDescGZIP(), []int{1}
}

func (x *EchoReply) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_grpc_echoer_proto protoreflect.FileDescriptor

const file_grpc_echoer_proto_rawDesc = "" +
	"\n" +
	"\x11grpc/echoer.proto\x12\x04grpc\"!\n" +
	"\vEchoRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"!\n" +
	"\tEchoReply\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply26\n" +
	"\x06Echoer\x12,\n" +
	"\x04Echo\x12\x11.grpc.EchoRequest\x1a\x0f.grpc.EchoReply\"\x00B$Z\"github.com/cockroachdb/errors/grpcb\x06proto3"

var (
	file_grpc_echoer_proto_rawDescOnce sync.Once
	file_grpc_echoer_proto_rawDescData []byte
)

func file_grpc_echoer_proto_rawDescGZIP() []byte {
	file_grpc_echoer_proto_rawDescOnce.Do(func() {
		file_grpc_echoer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_echoer_proto_rawDesc), len(file_grpc_echoer_proto_rawDesc)))
	})
	return file_grpc_echoer_proto_rawDescData
}

var file_grpc_echoer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_echoer_proto_goTypes = []any{
	(*EchoRequest)(nil), // 0: grpc.EchoRequest
	(*EchoReply)(nil),   // 1: grpc.EchoReply
}
var file_grpc_echoer_proto_depIdxs = []int32{
	0, // 0: grpc.Echoer.Echo:input_type -> grpc.EchoRequest
	1, // 1: grpc.Echoer.Echo:output_type -> grpc.EchoReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_echoer_proto_init() }
func file_grpc_echoer_proto_init() {
	if File_grpc_echoer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_echoer_proto_rawDesc), len(file_grpc_echoer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_echoer_proto_goTypes,
		DependencyIndexes: file_grpc_echoer_proto_depIdxs,
		MessageInfos:      file_grpc_echoer_proto_msgTypes,
	}.Build()
	File_grpc_echoer_proto = out.File
	file_grpc_echoer_proto_goTypes = nil
	file_grpc_echoer_proto_depIdxs = nil
}
