// Copyright 2019 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

// This package provides support for gRPC error handling. It has
// two main features:
//
// 1. Automatic en/decoding of gRPC Status errors via EncodeError and
//    DecodeError, enabled by importing the package.
//
// 2. Wrapping arbitrary errors with a gRPC status code via WrapWithGrpcCode()
//    and GetGrpcCode(). There is also a gRPC middleware in middleware/grpc
//    that will automatically do this (un)wrapping.
//
// Automatic en/decoding of gRPC Status errors is enabled by importing
// this package. Because EncodedError stores structured payloads in a
// google.protobuf.Any field, gRPC statuses are encoded via their
// standard google.rpc.Status representation
// (google.golang.org/genproto/googleapis/rpc/status), and all status
// details must be standard Protobuf messages registered with the
// protobuf global type registry.

package extgrpc

import (
	"context"
	"fmt"

	"github.com/cockroachdb/errors"
	"github.com/cockroachdb/errors/errbase"
	"github.com/cockroachdb/errors/markers"
	"github.com/cockroachdb/redact"
	spb "google.golang.org/genproto/googleapis/rpc/status"
	"google.golang.org/grpc/codes"
	grpcstatus "google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// withGrpcCode wraps an error with a gRPC status code.
type withGrpcCode struct {
	cause error
	code  codes.Code
}

// WrapWithGrpcCode wraps an error with a gRPC status code.
func WrapWithGrpcCode(err error, code codes.Code) error {
	if err == nil {
		return nil
	}
	return &withGrpcCode{cause: err, code: code}
}

// GetGrpcCode retrieves the gRPC code from a stack of causes.
func GetGrpcCode(err error) codes.Code {
	if err == nil {
		return codes.OK
	}
	if v, ok := markers.If(err, func(err error) (interface{}, bool) {
		if w, ok := err.(*withGrpcCode); ok {
			return w.code, true
		}
		return nil, false
	}); ok {
		return v.(codes.Code)
	}
	return codes.Unknown
}

// it's an error.
func (w *withGrpcCode) Error() string { return w.cause.Error() }

// it's also a wrapper.
func (w *withGrpcCode) Cause() error  { return w.cause }
func (w *withGrpcCode) Unwrap() error { return w.cause }

// it knows how to format itself.
func (w *withGrpcCode) Format(s fmt.State, verb rune) { errors.FormatError(w, s, verb) }

// SafeFormatter implements errors.SafeFormatter.
// Note: see the documentation of errbase.SafeFormatter for details
// on how to implement this. In particular beware of not emitting
// unsafe strings.
func (w *withGrpcCode) SafeFormatError(p errors.Printer) (next error) {
	if p.Detail() {
		p.Printf("gRPC code: %s", redact.Safe(w.code))
	}
	return w.cause
}

// it's an encodable error.
func encodeWithGrpcCode(_ context.Context, err error) (string, []string, proto.Message) {
	w := err.(*withGrpcCode)
	details := []string{fmt.Sprintf("gRPC %d", w.code)}
	payload := &EncodedGrpcCode{Code: uint32(w.code)}
	return "", details, payload
}

// it's a decodable error.
func decodeWithGrpcCode(
	_ context.Context, cause error, _ string, _ []string, payload proto.Message,
) error {
	wp := payload.(*EncodedGrpcCode)
	return &withGrpcCode{cause: cause, code: codes.Code(wp.Code)}
}

// encodeGrpcStatus takes an error generated by a standard gRPC Status and
// converts it into a standard Protobuf representation of google.rpc.Status
// (google.golang.org/genproto/googleapis/rpc/status).
//
// This is necessary since EncodedError uses an Any field for structured errors,
// and thus can only contain Protobufs that have been registered with the
// standard Protobuf type registry -- the standard gRPC Status type itself is
// not directly usable there, so it is converted to its google.rpc.Status
// representation, which is registered and can be decoded by DecodeError().
//
// Also note that in order to use error details, all details must be standard
// Protobuf types registered with the standard Protobuf type registry. The
// reasons for this are the same as for the Any field issue mentioned above.
func encodeGrpcStatus(_ context.Context, err error) (string, []string, proto.Message) {
	s := grpcstatus.Convert(err)
	// If there are known safe details, return them.
	details := []string{}
	for _, detail := range s.Details() {
		if safe, ok := detail.(errbase.SafeDetailer); ok {
			details = append(details, safe.SafeDetails()...)
		}
	}
	return s.Message(), details, s.Proto()
}

func decodeGrpcStatus(
	_ context.Context, _ string, _ []string, payload proto.Message,
) error {
	s, ok := payload.(*spb.Status)
	if !ok {
		// If input type was unexpected (shouldn't happen), we just return nil
		// which will cause DecodeError() to return an opaqueLeaf.
		return nil
	}
	return grpcstatus.FromProto(s).Err()
}

func init() {
	grpcError := grpcstatus.Error(codes.Unknown, "")
	errbase.RegisterLeafEncoder(errbase.GetTypeKey(grpcError), encodeGrpcStatus)
	errbase.RegisterLeafDecoder(errbase.GetTypeKey(grpcError), decodeGrpcStatus)

	errbase.RegisterWrapperEncoder(errbase.GetTypeKey((*withGrpcCode)(nil)), encodeWithGrpcCode)
	errbase.RegisterWrapperDecoder(errbase.GetTypeKey((*withGrpcCode)(nil)), decodeWithGrpcCode)
}
