// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: exthttp/ext_http.proto

package exthttp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncodedHTTPCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodedHTTPCode) Reset() {
	*x = EncodedHTTPCode{}
	mi := &file_exthttp_ext_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodedHTTPCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedHTTPCode) ProtoMessage() {}

func (x *EncodedHTTPCode) ProtoReflect() protoreflect.Message {
	mi := &file_exthttp_ext_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedHTTPCode.ProtoReflect.Descriptor instead.
func (*EncodedHTTPCode) Descriptor() ([]byte, []int) {
	return file_exthttp_ext_http_proto_rawDescGZIP(), []int{0}
}

func (x *EncodedHTTPCode) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_exthttp_ext_http_proto protoreflect.FileDescriptor

const file_exthttp_ext_http_proto_rawDesc = "" +
	"\n" +
	"\x16exthttp/ext_http.proto\x12\x18cockroach.errors.exthttp\"%\n" +
	"\x0fEncodedHTTPCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04codeB'Z%github.com/cockroachdb/errors/exthttpb\x06proto3"

var (
	file_exthttp_ext_http_proto_rawDescOnce sync.Once
	file_exthttp_ext_http_proto_rawDescData []byte
)

func file_exthttp_ext_http_proto_rawDescGZIP() []byte {
	file_exthttp_ext_http_proto_rawDescOnce.Do(func() {
		file_exthttp_ext_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exthttp_ext_http_proto_rawDesc), len(file_exthttp_ext_http_proto_rawDesc)))
	})
	return file_exthttp_ext_http_proto_rawDescData
}

var file_exthttp_ext_http_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exthttp_ext_http_proto_goTypes = []any{
	(*EncodedHTTPCode)(nil), // 0: cockroach.errors.exthttp.EncodedHTTPCode
}
var file_exthttp_ext_http_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exthttp_ext_http_proto_init() }
func file_exthttp_ext_http_proto_init() {
	if File_exthttp_ext_http_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exthttp_ext_http_proto_rawDesc), len(file_exthttp_ext_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exthttp_ext_http_proto_goTypes,
		DependencyIndexes: file_exthttp_ext_http_proto_depIdxs,
		MessageInfos:      file_exthttp_ext_http_proto_msgTypes,
	}.Build()
	File_exthttp_ext_http_proto = out.File
	file_exthttp_ext_http_proto_goTypes = nil
	file_exthttp_ext_http_proto_depIdxs = nil
}
