// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: errorspb/markers.proto

package errorspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MarkPayload is the error payload for a forced marker.
// See errors/markers/markers.go and the RFC on
// error handling for details.
type MarkPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Types         []*ErrorTypeMark       `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPayload) Reset() {
	*x = MarkPayload{}
	mi := &file_errorspb_markers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPayload) ProtoMessage() {}

func (x *MarkPayload) ProtoReflect() protoreflect.Message {
	mi := &file_errorspb_markers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPayload.ProtoReflect.Descriptor instead.
func (*MarkPayload) Descriptor() ([]byte, []int) {
	return file_errorspb_markers_proto_rawDescGZIP(), []int{0}
}

func (x *MarkPayload) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MarkPayload) GetTypes() []*ErrorTypeMark {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_errorspb_markers_proto protoreflect.FileDescriptor

const file_errorspb_markers_proto_rawDesc = "" +
	"\n" +
	"\x16errorspb/markers.proto\x12\x12cockroach.errorspb\x1a\x15errorspb/errors.proto\"X\n" +
	"\vMarkPayload\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x127\n" +
	"\x05types\x18\x02 \x03(\v2!.cockroach.errorspb.ErrorTypeMarkR\x05typesB(Z&github.com/cockroachdb/errors/errorspbb\x06proto3"

var (
	file_errorspb_markers_proto_rawDescOnce sync.Once
	file_errorspb_markers_proto_rawDescData []byte
)

func file_errorspb_markers_proto_rawDescGZIP() []byte {
	file_errorspb_markers_proto_rawDescOnce.Do(func() {
		file_errorspb_markers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errorspb_markers_proto_rawDesc), len(file_errorspb_markers_proto_rawDesc)))
	})
	return file_errorspb_markers_proto_rawDescData
}

var file_errorspb_markers_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_errorspb_markers_proto_goTypes = []any{
	(*MarkPayload)(nil),   // 0: cockroach.errorspb.MarkPayload
	(*ErrorTypeMark)(nil), // 1: cockroach.errorspb.ErrorTypeMark
}
var file_errorspb_markers_proto_depIdxs = []int32{
	1, // 0: cockroach.errorspb.MarkPayload.types:type_name -> cockroach.errorspb.ErrorTypeMark
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_errorspb_markers_proto_init() }
func file_errorspb_markers_proto_init() {
	if File_errorspb_markers_proto != nil {
		return
	}
	file_errorspb_errors_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errorspb_markers_proto_rawDesc), len(file_errorspb_markers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errorspb_markers_proto_goTypes,
		DependencyIndexes: file_errorspb_markers_proto_depIdxs,
		MessageInfos:      file_errorspb_markers_proto_msgTypes,
	}.Build()
	File_errorspb_markers_proto = out.File
	file_errorspb_markers_proto_goTypes = nil
	file_errorspb_markers_proto_depIdxs = nil
}
