// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: errorspb/tags.proto

package errorspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TagsPayload is the error payload for a WithContext
// marker.
// See errors/contexttags/withcontext.go and the RFC on
// error handling for details.
type TagsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*TagPayload          `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsPayload) Reset() {
	*x = TagsPayload{}
	mi := &file_errorspb_tags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsPayload) ProtoMessage() {}

func (x *TagsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_errorspb_tags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsPayload.ProtoReflect.Descriptor instead.
func (*TagsPayload) Descriptor() ([]byte, []int) {
	return file_errorspb_tags_proto_rawDescGZIP(), []int{0}
}

func (x *TagsPayload) GetTags() []*TagPayload {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TagPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagPayload) Reset() {
	*x = TagPayload{}
	mi := &file_errorspb_tags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagPayload) ProtoMessage() {}

func (x *TagPayload) ProtoReflect() protoreflect.Message {
	mi := &file_errorspb_tags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagPayload.ProtoReflect.Descriptor instead.
func (*TagPayload) Descriptor() ([]byte, []int) {
	return file_errorspb_tags_proto_rawDescGZIP(), []int{1}
}

func (x *TagPayload) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagPayload) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_errorspb_tags_proto protoreflect.FileDescriptor

const file_errorspb_tags_proto_rawDesc = "" +
	"\n" +
	"\x13errorspb/tags.proto\x12\x12cockroach.errorspb\"A\n" +
	"\vTagsPayload\x122\n" +
	"\x04tags\x18\x01 \x03(\v2\x1e.cockroach.errorspb.TagPayloadR\x04tags\"4\n" +
	"\n" +
	"TagPayload\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB(Z&github.com/cockroachdb/errors/errorspbb\x06proto3"

var (
	file_errorspb_tags_proto_rawDescOnce sync.Once
	file_errorspb_tags_proto_rawDescData []byte
)

func file_errorspb_tags_proto_rawDescGZIP() []byte {
	file_errorspb_tags_proto_rawDescOnce.Do(func() {
		file_errorspb_tags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errorspb_tags_proto_rawDesc), len(file_errorspb_tags_proto_rawDesc)))
	})
	return file_errorspb_tags_proto_rawDescData
}

var file_errorspb_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_errorspb_tags_proto_goTypes = []any{
	(*TagsPayload)(nil), // 0: cockroach.errorspb.TagsPayload
	(*TagPayload)(nil),  // 1: cockroach.errorspb.TagPayload
}
var file_errorspb_tags_proto_depIdxs = []int32{
	1, // 0: cockroach.errorspb.TagsPayload.tags:type_name -> cockroach.errorspb.TagPayload
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_errorspb_tags_proto_init() }
func file_errorspb_tags_proto_init() {
	if File_errorspb_tags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errorspb_tags_proto_rawDesc), len(file_errorspb_tags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errorspb_tags_proto_goTypes,
		DependencyIndexes: file_errorspb_tags_proto_depIdxs,
		MessageInfos:      file_errorspb_tags_proto_msgTypes,
	}.Build()
	File_errorspb_tags_proto = out.File
	file_errorspb_tags_proto_goTypes = nil
	file_errorspb_tags_proto_depIdxs = nil
}
