// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: errorspb/testing.proto

package errorspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TestError is meant for use in testing only.
type TestError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestError) Reset() {
	*x = TestError{}
	mi := &file_errorspb_testing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestError) ProtoMessage() {}

func (x *TestError) ProtoReflect() protoreflect.Message {
	mi := &file_errorspb_testing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestError.ProtoReflect.Descriptor instead.
func (*TestError) Descriptor() ([]byte, []int) {
	return file_errorspb_testing_proto_rawDescGZIP(), []int{0}
}

var File_errorspb_testing_proto protoreflect.FileDescriptor

const file_errorspb_testing_proto_rawDesc = "" +
	"\n" +
	"\x16errorspb/testing.proto\x12\x12cockroach.errorspb\"\v\n" +
	"\tTestErrorB(Z&github.com/cockroachdb/errors/errorspbb\x06proto3"

var (
	file_errorspb_testing_proto_rawDescOnce sync.Once
	file_errorspb_testing_proto_rawDescData []byte
)

func file_errorspb_testing_proto_rawDescGZIP() []byte {
	file_errorspb_testing_proto_rawDescOnce.Do(func() {
		file_errorspb_testing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errorspb_testing_proto_rawDesc), len(file_errorspb_testing_proto_rawDesc)))
	})
	return file_errorspb_testing_proto_rawDescData
}

var file_errorspb_testing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_errorspb_testing_proto_goTypes = []any{
	(*TestError)(nil), // 0: cockroach.errorspb.TestError
}
var file_errorspb_testing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errorspb_testing_proto_init() }
func file_errorspb_testing_proto_init() {
	if File_errorspb_testing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errorspb_testing_proto_rawDesc), len(file_errorspb_testing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errorspb_testing_proto_goTypes,
		DependencyIndexes: file_errorspb_testing_proto_depIdxs,
		MessageInfos:      file_errorspb_testing_proto_msgTypes,
	}.Build()
	File_errorspb_testing_proto = out.File
	file_errorspb_testing_proto_goTypes = nil
	file_errorspb_testing_proto_depIdxs = nil
}
